mybatis:
  mapper-locations:
    - classpath:mybatis/studentMapper.xml
  type-aliases-package: com.example.mybatisboot.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/reborn
    username : root
    password : 123456